include("template-app")
include("template-client")
include("template-datastore")
include("template-domain")
include("template-flyway")
include("template-services")
include("template-endpoints")
include("template-testkit")
